#ifndef SHOOTS_CONSTANTS_H
#define SHOOTS_CONSTANTS_H

// world stuff
#define SHOOTS_FRICTION .8
#define SHOOTS_BLOCK_SIZE 16
#define SHOOTS_WORLD_SIZE 64

// screen stuff
#define SHOOTS_SCREEN_WIDTH SHOOTS_BLOCK_SIZE * SHOOTS_WORLD_SIZE
#define SHOOTS_SCREEN_HEIGHT SHOOTS_BLOCK_SIZE * SHOOTS_WORLD_SIZE

// player stuff
#define SPLAYER_ACCEL 200
#define SPLAYER_MAX_SPEED SPLAYER_ACCEL * 3
#define SPLAYER_SIZE SHOOTS_BLOCK_SIZE

#endif
